
activities_new:
    pattern:  /new
    defaults: { _controller: TesisAdminBundle:Actividad:new}

activities_newform:
    pattern:  /newform
    defaults: { _controller: TesisAdminBundle:Actividad:newform }

activities_list:
    pattern:  /list
    defaults: { _controller: TesisAdminBundle:Actividad:list}
    options:
        expose: true

activities_check:
    pattern:  /{id}/check
    defaults: { _controller: TesisAdminBundle:Actividad:check}

activities_checkform:
    pattern:  /{id}/check_form
    defaults: { _controller: TesisAdminBundle:Actividad:checkform}

activities_edit:
    pattern:  /{id}/edit
    defaults: { _controller: TesisAdminBundle:Actividad:edit}

activities_editform:
    pattern:  /{id}/editform
    defaults: { _controller: TesisAdminBundle:Actividad:editform }

activities_delete:
    pattern:  /delete
    defaults: { _controller: TesisAdminBundle:Actividad:delete}
    options:
        expose: true 







