
activities_new:
    path:  /new
    defaults: { _controller: TesisAdminBundle:Actividad:new}

activities_newform:
    path:  /newform
    defaults: { _controller: TesisAdminBundle:Actividad:newform }

activities_list:
    path:  /list
    defaults: { _controller: TesisAdminBundle:Actividad:list}
    options:
        expose: true

activities_check:
    path:  /{id}/check
    defaults: { _controller: TesisAdminBundle:Actividad:check}

activities_checkform:
    path:  /{id}/check_form
    defaults: { _controller: TesisAdminBundle:Actividad:checkform}

activities_edit:
    path:  /{id}/edit
    defaults: { _controller: TesisAdminBundle:Actividad:edit}

activities_editform:
    path:  /{id}/editform
    defaults: { _controller: TesisAdminBundle:Actividad:editform }

activities_delete:
    path:  /delete
    defaults: { _controller: TesisAdminBundle:Actividad:delete}
    options:
        expose: true 







