coord_add:
    path:  /coord_add
    defaults: { _controller: TesisAdminBundle:Coordinadores:add}
    options:
        expose: true 

coord_addform:
    path:  /coord_addform
    defaults: { _controller: TesisAdminBundle:Coordinadores:addform}

coord_list:
    path:  /list
    defaults: { _controller: TesisAdminBundle:Coordinadores:list}
    options:
        expose: true

coord_check:
    path:  /{id}/check
    defaults: { _controller: TesisAdminBundle:Coordinadores:check}

coord_checkform:
    path:  /{id}/check_form
    defaults: { _controller: TesisAdminBundle:Coordinadores:checkform}

coord_edit:
    path:  /{id}/edit
    defaults: { _controller: TesisAdminBundle:Coordinadores:edit}

coord_editform:
    path:  /{id}/editform
    defaults: { _controller: TesisAdminBundle:Coordinadores:editform }






