
diario_new:
    pattern:  /new
    defaults: { _controller: TesisAdminBundle:Diario:new}

diario_newform:
    pattern:  /newform
    defaults: { _controller: TesisAdminBundle:Diario:newform}

diario_list:
    pattern:  /list
    defaults: { _controller: TesisAdminBundle:Diario:list}
    options:
        expose: true

diario_check:
    pattern:  /{id}/check
    defaults: { _controller: TesisAdminBundle:Diario:check}

diario_checkform:
    pattern:  /{id}/check_form
    defaults: { _controller: TesisAdminBundle:Diario:checkform}

diario_edit:
    pattern:  /{id}/edit
    defaults: { _controller: TesisAdminBundle:Diario:edit}

diario_editform:
    pattern:  /{id}/editform
    defaults: { _controller: TesisAdminBundle:Diario:editform }

diario_delete:
    pattern:  /delete
    defaults: { _controller: TesisAdminBundle:Diario:delete}
    options:
        expose: true 


