
diario_new:
    path:  /new
    defaults: { _controller: TesisAdminBundle:Diario:new}

diario_newform:
    path:  /newform
    defaults: { _controller: TesisAdminBundle:Diario:newform}

diario_list:
    path:  /list
    defaults: { _controller: TesisAdminBundle:Diario:list}
    options:
        expose: true

diario_check:
    path:  /{id}/check
    defaults: { _controller: TesisAdminBundle:Diario:check}

diario_checkform:
    path:  /{id}/check_form
    defaults: { _controller: TesisAdminBundle:Diario:checkform}

diario_edit:
    path:  /{id}/edit
    defaults: { _controller: TesisAdminBundle:Diario:edit}

diario_editform:
    path:  /{id}/editform
    defaults: { _controller: TesisAdminBundle:Diario:editform }

diario_delete:
    path:  /delete
    defaults: { _controller: TesisAdminBundle:Diario:delete}
    options:
        expose: true 

pdf_diario:
    path:  /{id}/pdf_diario
    defaults: { _controller: TesisAdminBundle:Diario:pdf_diario}


