
fase_new:
    path:  /new
    defaults: { _controller: TesisAdminBundle:Fase:new}

fase_newform:
    path:  /newform
    defaults: { _controller: TesisAdminBundle:Fase:newform }

fase_list:
    path:  /list
    defaults: { _controller: TesisAdminBundle:Fase:list}
    options:
        expose: true

fase_check:
    path:  /{id}/check
    defaults: { _controller: TesisAdminBundle:Fase:check}

fase_checkform:
    path:  /{id}/check_form
    defaults: { _controller: TesisAdminBundle:Fase:checkform}

fase_edit:
    path:  /{id}/edit
    defaults: { _controller: TesisAdminBundle:Fase:edit}

fase_editform:
    path:  /{id}/editform
    defaults: { _controller: TesisAdminBundle:Fase:editform }

fase_delete:
    path:  /delete
    defaults: { _controller: TesisAdminBundle:Fase:delete}
    options:
        expose: true 







