infofinal:
    path:  /info_final
    defaults: { _controller: TesisAdminBundle:InfoFinal:new_infofinal}
    options:
        expose: true

infofinal_pdf:
    path:  /{id}/info_finalpdf
    defaults: { _controller: TesisAdminBundle:InfoFinal:pdf_infofinal}

infofinal_list:
    path:  /list
    defaults: { _controller: TesisAdminBundle:InfoFinal:list}
    options:
        expose: true

infofinal_check:
    path:  /{id}/check
    defaults: { _controller: TesisAdminBundle:InfoFinal:check}

infofinal_checkform:
    path:  /{id}/check_form
    defaults: { _controller: TesisAdminBundle:InfoFinal:checkform}

infofinal_edit:
    path:  /{id}/edit
    defaults: { _controller: TesisAdminBundle:InfoFinal:edit}

infofinal_editform:
    path:  /{id}/editform
    defaults: { _controller: TesisAdminBundle:InfoFinal:editform }