


infoAdicional_new:
    pattern:  /new
    defaults: { _controller: TesisAdminBundle:InfoAdicional:new}

infoAdicional_newform:
    pattern:  /newform
    defaults: { _controller: TesisAdminBundle:InfoAdicional:newform}

infoAdicional_list:
    pattern:  /list
    defaults: { _controller: TesisAdminBundle:InfoAdicional:list}
    options:
        expose: true

infoAdicional_check:
    pattern:  /{id}/check
    defaults: { _controller: TesisAdminBundle:InfoAdicional:check}

infoAdicional_checkform:
    pattern:  /{id}/check_form
    defaults: { _controller: TesisAdminBundle:InfoAdicional:checkform}

infoAdicional_edit:
    pattern:  /{id}/edit
    defaults: { _controller: TesisAdminBundle:InfoAdicional:edit}

infoAdicional_editform:
    pattern:  /{id}/editform
    defaults: { _controller: TesisAdminBundle:InfoAdicional:editform }

infoAdicional_delete:
    pattern:  /delete
    defaults: { _controller: TesisAdminBundle:InfoAdicional:delete}
    options:
        expose: true 
