


infoAdicional_new:
    path:  /new
    defaults: { _controller: TesisAdminBundle:InfoAdicional:new}

infoAdicional_newform:
    path:  /newform
    defaults: { _controller: TesisAdminBundle:InfoAdicional:newform}

infoAdicional_list:
    path:  /list
    defaults: { _controller: TesisAdminBundle:InfoAdicional:list}
    options:
        expose: true

infoAdicional_check:
    path:  /{id}/check
    defaults: { _controller: TesisAdminBundle:InfoAdicional:check}

infoAdicional_checkform:
    path:  /{id}/check_form
    defaults: { _controller: TesisAdminBundle:InfoAdicional:checkform}

infoAdicional_edit:
    path:  /{id}/edit
    defaults: { _controller: TesisAdminBundle:InfoAdicional:edit}

infoAdicional_editform:
    path:  /{id}/editform
    defaults: { _controller: TesisAdminBundle:InfoAdicional:editform }

infoAdicional_delete:
    path:  /delete
    defaults: { _controller: TesisAdminBundle:InfoAdicional:delete}
    options:
        expose: true 
