laborsc_add:
    path:  /laborsc_add
    defaults: { _controller: TesisAdminBundle:Laborsc:add}
    options:
        expose: true 

laborsc_addform:
    path:  /laborsc_addform
    defaults: { _controller: TesisAdminBundle:Laborsc:addform}

laborsc_list:
    path:  /list
    defaults: { _controller: TesisAdminBundle:Laborsc:list}
    options:
        expose: true

laborsc_check:
    path:  /{id}/check
    defaults: { _controller: TesisAdminBundle:Laborsc:check}

laborsc_checkform:
    path:  /{id}/check_form
    defaults: { _controller: TesisAdminBundle:Laborsc:checkform}

laborsc_edit:
    path:  /{id}/edit
    defaults: { _controller: TesisAdminBundle:Laborsc:edit}

laborsc_editform:
    path:  /{id}/editform
    defaults: { _controller: TesisAdminBundle:Laborsc:editform }






