
reports_1:
    pattern:  /reports1
    defaults: { _controller: TesisAdminBundle:Reports:new_reports1}

report1form:
    pattern:  /reportform
    defaults: { _controller: TesisAdminBundle:Reports:report1form}

reports_1pdf:
    pattern:  /reports1pdf
    defaults: { _controller: TesisAdminBundle:Reports:pdf_reports1}

reports_2:
    pattern:  /reports2
    defaults: { _controller: TesisAdminBundle:Reports:new_reports2}

report2form:
    pattern:  /reportform
    defaults: { _controller: TesisAdminBundle:Reports:report2form}

reports_2pdf:
    pattern:  /reports2pdf
    defaults: { _controller: TesisAdminBundle:Reports:pdf_reports2}

reports_3:
    pattern:  /reports3
    defaults: { _controller: TesisAdminBundle:Reports:new_reports3}

report3form:
    pattern:  /reportform
    defaults: { _controller: TesisAdminBundle:Reports:report3form}

reports_3pdf:
    pattern:  /reports3pdf
    defaults: { _controller: TesisAdminBundle:Reports:pdf_reports3}

reports_4:
    pattern:  /reports4
    defaults: { _controller: TesisAdminBundle:Reports:new_reports4}

reports_4pdf:
    pattern:  /reports4pdf
    defaults: { _controller: TesisAdminBundle:Reports:pdf_reports4}

reports_5:
    pattern:  /reports5
    defaults: { _controller: TesisAdminBundle:Reports:new_reports5}

reports_5pdf:
    pattern:  /reports5pdf
    defaults: { _controller: TesisAdminBundle:Reports:pdf_reports5}
