
adicionales_new:
    pattern:  /new
    defaults: { _controller: TesisAdminBundle:Adicionales:new}

adicionales_newform:
    pattern:  /newform
    defaults: { _controller: TesisAdminBundle:Adicionales:newform}

adicionales_list:
    pattern:  /list
    defaults: { _controller: TesisAdminBundle:Adicionales:list}
    options:
        expose: true

adicionales_check:
    pattern:  /{id}/check
    defaults: { _controller: TesisAdminBundle:Adicionales:check}

adicionales_checkform:
    pattern:  /{id}/check_form
    defaults: { _controller: TesisAdminBundle:Adicionales:checkform}

adicionales_edit:
    pattern:  /{id}/edit
    defaults: { _controller: TesisAdminBundle:Adicionales:edit}

adicionales_editform:
    pattern:  /{id}/editform
    defaults: { _controller: TesisAdminBundle:Adicionales:editform }

adicionales_delete:
    pattern:  /delete
    defaults: { _controller: TesisAdminBundle:Adicionales:delete}
    options:
        expose: true 


