
student_checkform:
    path:  /{id}/check_formst
    defaults: { _controller: TesisAdminBundle:Estudiante:checkform}
    options:
        expose: true

student_delete:
    path:  /deletest
    defaults: { _controller: TesisAdminBundle:Estudiante:delete}
    options:
        expose: true 

student_editform:
    path:  /{id}/editformst
    defaults: { _controller: TesisAdminBundle:Estudiante:editform }
    options:
        expose: true    

student_editpassform:
    path:  /{cedula}/edit_pass_formst
    defaults: { _controller: TesisAdminBundle:Estudiante:editpassform}
    options:
        expose: true

student_new:
    path:  /student_new
    defaults: { _controller: TesisAdminBundle:Estudiante:new}
    options:
        expose: true


student_newform:
    path:  /student_form
    defaults: { _controller: TesisAdminBundle:Estudiante:newform}
    options:
        expose: true



student_new_alfa:
    path:  /{nameLogin}/{clave}/useralfa_new
    defaults: { _controller: TesisAdminBundle:Estudiante:new_alfa}
    options:
        expose: true


student_newform_alfa:
    path:  /{nameLogin}/{clave}/user_newalfa
    defaults: { _controller: TesisAdminBundle:Estudiante:newform_alfa}
    options:
        expose: true