
periodo_new:
    path:  /new
    defaults: { _controller: TesisAdminBundle:Periodo:new}

periodo_newform:
    path:  /newform
    defaults: { _controller: TesisAdminBundle:Periodo:newform }

periodo_list:
    path:  /list
    defaults: { _controller: TesisAdminBundle:Periodo:list}
    options:
        expose: true

periodo_check:
    path:  /{id}/check
    defaults: { _controller: TesisAdminBundle:Periodo:check}

periodo_checkform:
    path:  /{id}/check_form
    defaults: { _controller: TesisAdminBundle:Periodo:checkform}

periodo_edit:
    path:  /{id}/edit
    defaults: { _controller: TesisAdminBundle:Periodo:edit}

periodo_editform:
    path:  /{id}/editform
    defaults: { _controller: TesisAdminBundle:Periodo:editform }

periodo_delete:
    path:  /delete
    defaults: { _controller: TesisAdminBundle:Periodo:delete}
    options:
        expose: true 




