tutors_add:
    pattern:  /tutors_add
    defaults: { _controller: TesisAdminBundle:Tutores:add}
    options:
        expose: true 

tutors_addform:
    pattern:  /tutors_addform
    defaults: { _controller: TesisAdminBundle:Tutores:addform}

tutors_list:
    pattern:  /list
    defaults: { _controller: TesisAdminBundle:Tutores:list}
    options:
        expose: true

tutors_check:
    pattern:  /{id}/check
    defaults: { _controller: TesisAdminBundle:Tutores:check}

tutors_checkform:
    pattern:  /{id}/check_form
    defaults: { _controller: TesisAdminBundle:Tutores:checkform}

tutors_edit:
    pattern:  /{id}/edit
    defaults: { _controller: TesisAdminBundle:Tutores:edit}

tutors_editform:
    pattern:  /{id}/editform
    defaults: { _controller: TesisAdminBundle:Tutores:editform }


# eliecer fuck
tutores_select:
    pattern:  /{id}/tutores_select
    defaults: { _controller: TesisAdminBundle:Tutores:editSelect}
    options:
        expose: true 



