<?php

namespace Proxies\__CG__\Tesis\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Periodo extends \Tesis\AdminBundle\Entity\Periodo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'nombre', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'fechaInicio', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'fechaFin', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'comentario', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'calificacion', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'observacion', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'idPeriodo', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'estudianteEstudiante', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'actividadActividad');
        }

        return array('__isInitialized__', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'nombre', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'fechaInicio', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'fechaFin', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'comentario', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'calificacion', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'observacion', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'idPeriodo', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'estudianteEstudiante', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Periodo' . "\0" . 'actividadActividad');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Periodo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaInicio($fechaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaInicio', array($fechaInicio));

        return parent::setFechaInicio($fechaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInicio', array());

        return parent::getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFin($fechaFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFin', array($fechaFin));

        return parent::setFechaFin($fechaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFin', array());

        return parent::getFechaFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setComentario($comentario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComentario', array($comentario));

        return parent::setComentario($comentario);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentario', array());

        return parent::getComentario();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalificacion($calificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalificacion', array($calificacion));

        return parent::setCalificacion($calificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalificacion', array());

        return parent::getCalificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', array($observacion));

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', array());

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPeriodo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPeriodo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPeriodo', array());

        return parent::getIdPeriodo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstudianteEstudiante(\Tesis\AdminBundle\Entity\Estudiante $estudianteEstudiante = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstudianteEstudiante', array($estudianteEstudiante));

        return parent::setEstudianteEstudiante($estudianteEstudiante);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstudianteEstudiante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstudianteEstudiante', array());

        return parent::getEstudianteEstudiante();
    }

    /**
     * {@inheritDoc}
     */
    public function addActividadActividad(\Tesis\AdminBundle\Entity\Actividad $actividadActividad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActividadActividad', array($actividadActividad));

        return parent::addActividadActividad($actividadActividad);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActividadActividad(\Tesis\AdminBundle\Entity\Actividad $actividadActividad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActividadActividad', array($actividadActividad));

        return parent::removeActividadActividad($actividadActividad);
    }

    /**
     * {@inheritDoc}
     */
    public function getActividadActividad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActividadActividad', array());

        return parent::getActividadActividad();
    }

}
