<?php

namespace Proxies\__CG__\Tesis\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Diario extends \Tesis\AdminBundle\Entity\Diario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'fecha', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'personal', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'fortalezas', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'debilidades', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'conclusion', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'horaInicio', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'horaFin', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'persona', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'calificacion', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'observacion', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'horas', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'ninos', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'adultos', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'terceraEdad', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'discapacidad', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'comunidad', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'descripcion', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'idDiario', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'periodoPeriodo', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'estudianteEstudiante', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'actividadActividad');
        }

        return array('__isInitialized__', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'fecha', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'personal', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'fortalezas', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'debilidades', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'conclusion', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'horaInicio', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'horaFin', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'persona', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'calificacion', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'observacion', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'horas', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'ninos', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'adultos', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'terceraEdad', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'discapacidad', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'comunidad', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'descripcion', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'idDiario', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'periodoPeriodo', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'estudianteEstudiante', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Diario' . "\0" . 'actividadActividad');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Diario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonal($personal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonal', array($personal));

        return parent::setPersonal($personal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonal', array());

        return parent::getPersonal();
    }

    /**
     * {@inheritDoc}
     */
    public function setFortalezas($fortalezas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFortalezas', array($fortalezas));

        return parent::setFortalezas($fortalezas);
    }

    /**
     * {@inheritDoc}
     */
    public function getFortalezas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFortalezas', array());

        return parent::getFortalezas();
    }

    /**
     * {@inheritDoc}
     */
    public function setDebilidades($debilidades)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDebilidades', array($debilidades));

        return parent::setDebilidades($debilidades);
    }

    /**
     * {@inheritDoc}
     */
    public function getDebilidades()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDebilidades', array());

        return parent::getDebilidades();
    }

    /**
     * {@inheritDoc}
     */
    public function setConclusion($conclusion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConclusion', array($conclusion));

        return parent::setConclusion($conclusion);
    }

    /**
     * {@inheritDoc}
     */
    public function getConclusion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConclusion', array());

        return parent::getConclusion();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraInicio($horaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraInicio', array($horaInicio));

        return parent::setHoraInicio($horaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraInicio', array());

        return parent::getHoraInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraFin($horaFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraFin', array($horaFin));

        return parent::setHoraFin($horaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraFin', array());

        return parent::getHoraFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersona($persona)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersona', array($persona));

        return parent::setPersona($persona);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersona', array());

        return parent::getPersona();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalificacion($calificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalificacion', array($calificacion));

        return parent::setCalificacion($calificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalificacion', array());

        return parent::getCalificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', array($observacion));

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', array());

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoras($horas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoras', array($horas));

        return parent::setHoras($horas);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoras', array());

        return parent::getHoras();
    }

    /**
     * {@inheritDoc}
     */
    public function setNinos($ninos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNinos', array($ninos));

        return parent::setNinos($ninos);
    }

    /**
     * {@inheritDoc}
     */
    public function getNinos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNinos', array());

        return parent::getNinos();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdultos($adultos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdultos', array($adultos));

        return parent::setAdultos($adultos);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdultos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdultos', array());

        return parent::getAdultos();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerceraEdad($terceraEdad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerceraEdad', array($terceraEdad));

        return parent::setTerceraEdad($terceraEdad);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerceraEdad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerceraEdad', array());

        return parent::getTerceraEdad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscapacidad($discapacidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscapacidad', array($discapacidad));

        return parent::setDiscapacidad($discapacidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscapacidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscapacidad', array());

        return parent::getDiscapacidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setComunidad($comunidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComunidad', array($comunidad));

        return parent::setComunidad($comunidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getComunidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComunidad', array());

        return parent::getComunidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDiario($idDiario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDiario', array($idDiario));

        return parent::setIdDiario($idDiario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDiario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdDiario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDiario', array());

        return parent::getIdDiario();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodoPeriodo(\Tesis\AdminBundle\Entity\Periodo $periodoPeriodo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodoPeriodo', array($periodoPeriodo));

        return parent::setPeriodoPeriodo($periodoPeriodo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodoPeriodo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodoPeriodo', array());

        return parent::getPeriodoPeriodo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstudianteEstudiante(\Tesis\AdminBundle\Entity\Estudiante $estudianteEstudiante = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstudianteEstudiante', array($estudianteEstudiante));

        return parent::setEstudianteEstudiante($estudianteEstudiante);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstudianteEstudiante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstudianteEstudiante', array());

        return parent::getEstudianteEstudiante();
    }

    /**
     * {@inheritDoc}
     */
    public function addActividadActividad(\Tesis\AdminBundle\Entity\Actividad $actividadActividad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActividadActividad', array($actividadActividad));

        return parent::addActividadActividad($actividadActividad);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActividadActividad(\Tesis\AdminBundle\Entity\Actividad $actividadActividad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActividadActividad', array($actividadActividad));

        return parent::removeActividadActividad($actividadActividad);
    }

    /**
     * {@inheritDoc}
     */
    public function getActividadActividad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActividadActividad', array());

        return parent::getActividadActividad();
    }

}
