<?php

namespace Proxies\__CG__\Tesis\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Estudiante extends \Tesis\AdminBundle\Entity\Estudiante implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'nombre', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'apellido', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'cedula', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'clave', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'correo', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'telefono', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'sc', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'genero', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'perfil', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'nameLogin', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'departamento', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'semestre', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'periodo', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'estatus', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'profesor', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'proyecto', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'idEstudiante', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'tutoriaTutoria', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'laborscLaborsc');
        }

        return array('__isInitialized__', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'nombre', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'apellido', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'cedula', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'clave', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'correo', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'telefono', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'sc', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'genero', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'perfil', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'nameLogin', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'departamento', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'semestre', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'periodo', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'estatus', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'profesor', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'proyecto', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'idEstudiante', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'tutoriaTutoria', '' . "\0" . 'Tesis\\AdminBundle\\Entity\\Estudiante' . "\0" . 'laborscLaborsc');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Estudiante $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido($apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', array($apellido));

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', array());

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setCedula($cedula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCedula', array($cedula));

        return parent::setCedula($cedula);
    }

    /**
     * {@inheritDoc}
     */
    public function getCedula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCedula', array());

        return parent::getCedula();
    }

    /**
     * {@inheritDoc}
     */
    public function setClave($clave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClave', array($clave));

        return parent::setClave($clave);
    }

    /**
     * {@inheritDoc}
     */
    public function getClave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClave', array());

        return parent::getClave();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo($correo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', array($correo));

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', array());

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setSc($sc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSc', array($sc));

        return parent::setSc($sc);
    }

    /**
     * {@inheritDoc}
     */
    public function getSc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSc', array());

        return parent::getSc();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenero($genero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenero', array($genero));

        return parent::setGenero($genero);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenero', array());

        return parent::getGenero();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerfil($perfil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerfil', array($perfil));

        return parent::setPerfil($perfil);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerfil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerfil', array());

        return parent::getPerfil();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameLogin($nameLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameLogin', array($nameLogin));

        return parent::setNameLogin($nameLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameLogin', array());

        return parent::getNameLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartamento($departamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartamento', array($departamento));

        return parent::setDepartamento($departamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartamento', array());

        return parent::getDepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setSemestre($semestre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSemestre', array($semestre));

        return parent::setSemestre($semestre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSemestre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSemestre', array());

        return parent::getSemestre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodo($periodo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodo', array($periodo));

        return parent::setPeriodo($periodo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodo', array());

        return parent::getPeriodo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstatus($estatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstatus', array($estatus));

        return parent::setEstatus($estatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstatus', array());

        return parent::getEstatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesor($profesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesor', array($profesor));

        return parent::setProfesor($profesor);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesor', array());

        return parent::getProfesor();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyecto($proyecto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyecto', array($proyecto));

        return parent::setProyecto($proyecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyecto', array());

        return parent::getProyecto();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addTutoriaTutorium(\Tesis\AdminBundle\Entity\Tutoria $tutoriaTutoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTutoriaTutorium', array($tutoriaTutoria));

        return parent::addTutoriaTutorium($tutoriaTutoria);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTutoriaTutorium(\Tesis\AdminBundle\Entity\Tutoria $tutoriaTutoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTutoriaTutorium', array($tutoriaTutoria));

        return parent::removeTutoriaTutorium($tutoriaTutoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getTutoriaTutoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTutoriaTutoria', array());

        return parent::getTutoriaTutoria();
    }

    /**
     * {@inheritDoc}
     */
    public function addLaborscLaborsc(\Tesis\AdminBundle\Entity\Laborsc $laborscLaborsc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLaborscLaborsc', array($laborscLaborsc));

        return parent::addLaborscLaborsc($laborscLaborsc);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLaborscLaborsc(\Tesis\AdminBundle\Entity\Laborsc $laborscLaborsc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLaborscLaborsc', array($laborscLaborsc));

        return parent::removeLaborscLaborsc($laborscLaborsc);
    }

    /**
     * {@inheritDoc}
     */
    public function getLaborscLaborsc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLaborscLaborsc', array());

        return parent::getLaborscLaborsc();
    }

}
